### ISSUE TITLE
Create the data type to accumulate and aply config info

### ISSUE THREAD

**Issue by vrom911** [kowainik/stan#120]
We will need a way to filter files/inspections/observations based on the config.

**Comment by chshersh** [comment]
We discussed, that the possible data type that reflects `Config` could be `HashMap FilePath (Slist Inspection)`. As to semantics of the `Include` and `Ignore`: this is becoming tricky. By default, we are working with all Inspections, and the use-case I'm imagining is the people will ignore some of the inspections for some files. But how they can ignore all inspections and enable only some specific ones? There are several possible options:

1. Add `ChechEverything` `CheckFilter` and `CheckEverywhere` `CheckScope` to specify explicitly. To ignore all inspections, the first entry should be:
    ```toml
    [[check]]
    type = "Ignore"
    what = "everything"  # ??? Dunno, how to specify this ???
    where = "everywhere"  # ??? Dunno, how to specify this ???
    ```
2. If `CheckScope` is not specified, we assume that the rule is applied to all files. The same goes for `CheckFilter`. With this approach, the following `check` will disable all inspections:
    ```toml
    [[check]]
    type = "Ignore"
    ```

Thoughts and ideas?
