### ISSUE TITLE
Support list of inspections and list of files in the config and CLI

### ISSUE THREAD

**Issue by chshersh** [kowainik/stan#151]

**Comment by chshersh** [comment]
I'm thinking that our codecs can be smart and support both: single entry and list of entries. So the following will be valid:

```toml
[[check]]
type = "Ignore"
category = "Partial"

[[check]]
type = "Include"
categories = [ "Partial", "List" ]  # or should it also be named 'category'?
```
