### ISSUE TITLE
Explicit 'CheckFilter' and 'CheckScope'

### ISSUE THREAD

**Issue by chshersh** [kowainik/stan#159]
As discussed with @vrom911, currently, when `CheckFilter` or `CheckScope` are not specified, the semantic of this is _all_. This can be confusing sometimes. We can introduce new constructors for both `CheckFilter` and `CheckScope` to explicitly specify the filter and scope with the **all** meaning. Specifically:

```haskell
data CheckFilter
   = ...
   | CheckAll

data CheckScope
    = ...
    | CheckScopeAll
```

And in TOML it will look like this:

```toml
[[check]]
type = "Ignore"
filter = "all"
scope = "all"
```
