### ISSUE TITLE
Documentation for CI integration

### ISSUE THREAD

**Issue by TristanCacqueray** [kowainik/stan#438]
How would you recommend to use stan as a continuous integration test?
Assuming this is correct, could we add such snippets to the README?

```yaml
      - run: cabal v2-install stan --install-method=copy --overwrite-policy=always
      - run: stan report
      - uses: actions/upload-artifact@v2
        with:
          name: stan-report
          path: ./stan.html
```
